
# Workflow ka naam jo GitHub Actions me show hoga
name: CI/CD Pipeline

# Workflow kab trigger hoga
on:

# Jab code push hoga
  push:
    branches:
      - develop
      - main
    
    paths-ignore:
      - 'README.md'

   # Jab Pull Request create ya update hogi    
  pull_request:
    branches:
      - develop
      - main

    paths-ignore:
      - 'README.md'

# Yahan se jobs start hoti hain
jobs:

  # CI Job
  ci:
    name:    Test & Build
    runs-on: ubuntu-latest

   
    steps:

      - name: checkout repository
        uses: actions/checkout@v4

  
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      
      - name: Install Dependencies
        run:  npm install


      - name: Run Unit Tests
        run:  npm test

      - name: Run GitLeaks Scan
        run:  gitleaks/gitleaks-action@v3


  # Docker Job 
  docker:
    name:    Build & Push Docker Image
    runs-on: ubuntu-latest
    needs:   ci

    steps: 

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run:  echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME}}"
        
      - name: Build Docker Images
        run:  docker build -t ${{secrets.DOCKER.DOCKER_USERNAME}}/node-crud-app .

      - name: Run Trivy Scan 
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/node-crud-app
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

  # Deployment on EC2 Staging & Production 
  
